controllers:
    resource: ../src/Controller/
    type: attribute

app_homepage:
    path: /
    controller: App\Controller\DefaultController::index
    methods: [GET]
    requirements:
        _locale: fr|en

app_react:
    path: /{reactRouting}
    controller: App\Controller\TicTacToeController::index
    requirements:
        reactRouting: '^(?!api|_(wdt|profiler|error)).*'
